import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#222',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: -20,
    marginHorizontal: '3%',
  },
  backButtonIcon: {
    marginRight: 2,
    color: 'white',
  },
  title: {
    fontSize: 25,
    color: 'white',
    fontWeight: 'bold',
  },
  line: {
    marginTop: 15,
    marginBottom: 10,
  },
  inputContainer: {
    width: '90%',
    marginHorizontal: '5%',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  inputLabel: {
    marginRight: 30,
    color: 'white',
  },
  textInput: {
    flex: 1,
    height: 39,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
    color: 'white',
  },
  dateInput: {
    flex: 1,
    marginRight: 10,
    height: 39,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 10,
  },
  timeInput: {
    flex: 1,
    height: 39,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 10,
  },
  locationInput: {
    flex: 1,
    height: 39,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 6,
    justifyContent: 'center',
    paddingLeft: 10,
  },
  button: {
    // marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 1,
    borderRadius: 10,
    backgroundColor: 'white',
    width: 147,
    height: 43,
    lineHeight: 43,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: 'bold',
  },
  partyDescription: {
    height: 150,
    borderColor: 'gray',
    borderWidth: 1,
    marginTop: 10,
    borderRadius: 6,
    color: 'white',
    textAlignVertical: 'top',
  },
  photoUpload: {
    flexDirection: 'row',
    marginTop: 10,
    alignItems: 'center',
  },
  photoCameraButton: {
    borderColor: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 69,
    width: 80,
    backgroundColor: '#ccc',
    marginRight: 10,
  },
  photoThumbnail: {
    borderColor: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 69,
    width: 80,
    backgroundColor: '#ccc',
    marginRight: 3,
  },
  photoModalContainer: {
    flex: 1,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoModalImage: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
  },
});